### Package Imports

In [1]:
import numpy as np

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [2]:
import numpy as np
my_list = [x * 10 for x in range(1, 11)]
my_array = np.array(my_list)
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [3]:
my_array.ndim

1

In [4]:
my_array.shape

(10,)

In [5]:
my_array.size

10

In [6]:
my_array.dtype

dtype('int32')

# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [7]:
arrays_2d = np.arange(1,11,1, dtype = int).reshape(5,2)*10
arrays_2d

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [8]:
my_array = np.linspace(10,100,10 , dtype = int).reshape(5,2)
my_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [9]:
my_array2 = 

SyntaxError: invalid syntax (3975956327.py, line 1)

In [10]:
array_2d = np.array([range(5) , range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

In [11]:
rng = np.random.default_rng(2022)
random_array = rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second selement of the third row.

Thanks!


In [12]:
random_array[0:2,]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [13]:
random_array[ : , 1]

array([0.09299006, 0.66103343, 0.04305584])

In [14]:
random_array[2,2]

0.41441747385528926

# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [15]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [16]:
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [17]:
discount_pct = random_array[:2].reshape(6)
discount_pct

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778])

In [18]:
percent_owed = 1 - discount_pct
percent_owed

array([0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
       0.24484222])

In [19]:
final_amount_owed = percent_owed * total
final_amount_owed.round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

# Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [20]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [21]:
prices >25

array([False, False, False,  True, False,  True])

In [22]:
prices[prices > 25]

array([99.99, 49.99])

In [23]:
products[prices>24]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [24]:
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [25]:
products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [26]:
{k:w for k,w in zip(products,prices)}['cola']

4.99

In [27]:
products[(prices > 25) | (prices  == 4.99)]

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [28]:
fancy_feast_special = products[(prices > 25) | (products == 'cola')]
fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [29]:
shipping_cost = np.where(prices > 20 , 0, 5)
shipping_cost


array([5, 5, 0, 0, 5, 0])

# Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list. 

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.

In [35]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [38]:
sorted_prices = np.sort(prices)
print(sorted_prices)

[ 4.99  5.99  6.99 22.49 49.99 99.99]


In [44]:
len(sorted_prices)

6

In [62]:
top3 = sorted_prices[len(sorted_prices)-3: ]
top3

array([22.49, 49.99, 99.99])

In [72]:
top_3_stats = np.array(['Max:' , top3.max() , 'Min:', top3.mean() , 'Mean:' , top3.mean()]).T
top_3_stats

array(['Max:', '99.99', 'Min:', '57.49', 'Mean:', '57.49'], dtype='<U32')

In [74]:
print(f"Mean:{top3.mean()}")
print(f"Max:{top3.max()}")
print(f"Min:{top3.min()}")
print(f"Median:{np.median(top3)}")

Mean:57.49
Max:99.99
Min:22.49
Median:49.99


In [59]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

In [61]:
unique_tiers = np.unique(price_tiers)
unique_tiers

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

# Assignment 7: Bringing it All Together

Ok, final NumPy task - let's read in some data with the help of Pandas.

Our data scientist provided the code to read in a csv as a Pandas dataframe, and has converted the two columns of interest to arrays.

* Filter `sales_array` down to only sales where the product family was produce. 

* Then, randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

* Finally, create a new array that has the values 'above_both', 'above_median', and 'below_both' based on whether the sales were above the median and mean of the sample, just above the median of the sample, or below both the median and mean of the sample. 

In [78]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "D:\\AA\\Programming\\Data Science\\Python\\Maven\\Data Analysis With Python AND Pandas\\Pandas+Course+Resources\\Pandas Course Resources\\retail\\retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

In [79]:
retail_df

id        date  store_nbr               family    sales  onpromotion
0    1956943  2016-01-07         18                 EGGS   177.00            0
1    1956944  2016-01-07         18         FROZEN FOODS    36.00            0
2    1956945  2016-01-07         18            GROCERY I  2291.06            6
3    1956946  2016-01-07         18           GROCERY II    16.00            0
4    1956947  2016-01-07         18             HARDWARE     2.00            0
..       ...         ...        ...                  ...      ...          ...
995  1957938  2016-01-07         45   HOME AND KITCHEN I    83.00            0
996  1957939  2016-01-07         45  HOME AND KITCHEN II    97.00            1
997  1957940  2016-01-07         45      HOME APPLIANCES     1.00            0
998  1957941  2016-01-07         45            HOME CARE   510.00            1
999  1957942  2016-01-07         45           LADIESWEAR     4.00            0

[1000 rows x 6 columns]

In [85]:
sales_array

array([1.77000000e+02, 3.60000000e+01, 2.29106000e+03, 1.60000000e+01,
       2.00000000e+00, 1.20000000e+01, 7.00000000e+00, 0.00000000e+00,
       1.94000000e+02, 3.00000000e+00, 2.00000000e+00, 6.00000000e+00,
       4.60000000e+01, 1.00000000e+00, 2.18416000e+02, 1.84000000e+02,
       4.00000000e+00, 1.00000000e+00, 2.63230000e+02, 5.10000000e+01,
       1.66239400e+03, 0.00000000e+00, 6.53600030e+00, 1.00000000e+01,
       0.00000000e+00, 2.00000000e+00, 3.03300000e+03, 0.00000000e+00,
       1.61000000e+02, 1.20000000e+01, 7.18000000e+02, 2.67000000e+02,
       2.80000000e+02, 2.70000000e+01, 4.70000000e+01, 2.45300000e+03,
       2.00000000e+00, 1.00000000e+00, 2.20000000e+01, 8.00000000e+00,
       0.00000000e+00, 1.39000000e+02, 1.00000000e+00, 0.00000000e+00,
       2.00000000e+00, 4.60000000e+01, 1.00000000e+00, 1.68847000e+02,
       1.90000000e+02, 0.00000000e+00, 0.00000000e+00, 2.18873000e+02,
       4.60000000e+01, 4.47064000e+02, 0.00000000e+00, 4.00000000e+00,
      

In [113]:
produce_sales = sales_array[(family_array == 'PRODUCE')]
produce_sales.size

30

In [96]:
remain_sales = sales_array[(family_array != 'PRODUCE')]
print(f"Mean of remain_sale: {np.round(remain_sales.mean(),2)}")
print(f"Median of remin_sales:{np.round(np.median(remain_sales),2)}")

Mean of remain_sale: 295.36
Median of remin_sales:16.0


In [98]:
print(f"Mean of remain_sale: {np.round(prodec_sales.mean(),2)}")
print(f"Median of remin_sales:{np.round(np.median(prodec_sales),2)}")

Mean of remain_sale: 1730.98
Median of remin_sales:1122.35


In [153]:
rng = np.random.default_rng(2022)
rand_array = np.round(rng.random(produce_sales.size),2)
rand_sample = produce_sales[rand_array < 0.5]
rand_sample.size

17

In [147]:
print(f"Mean of random sample:{np.round(rand_sample.mean(),2)}")
print(f"Median of random sample:{np.round(np.median(rand_sample),2)}")

Mean of random sample:2268.1
Median of random sample:1272.76


In [148]:
sample_mean = np.round(rand_sample.mean(),2)
sample_median = np.round(np.median(rand_sample),2)

In [133]:
above_both = np.where((rand_sample > sample_mean) , "above_both")
above_median = np.where((rand_sample > sample_median) & (rand_sample < sample_mean) , "just above the median" , None)
below_both = np.where((rand_sample < sample_median) & (rand_sample < sample_mean) , "below both" , None)

In [152]:
categorized_list = np.where((rand_sample > sample_mean) , "above_both" , 
                           np.where((rand_sample > sample_median) & (rand_sample < sample_mean) , "just above the median",
                                   "below both"))
categorized_list

array(['just above the median', 'below both', 'below both', 'below both',
       'above_both', 'below both', 'below both', 'above_both',
       'below both', 'below both', 'above_both', 'above_both',
       'below both', 'just above the median', 'above_both', 'below both',
       'above_both'], dtype='<U21')